// 统一管理mutations名称
export const INIT_SONGLIST = 'INIT_SONGLIST',
    INIT_PLAYER = 'INIT_PLAYER',
    TOGGLE_REPEAT = 'TOGGLE_REPEAT',
    TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE',
    PLAY = 'PLAY',
    SET_PLAYING = 'SET_PLAYING',
    SET_PAUSE = 'PAUSE',
    SELECT_TRACK = 'SELECT_TRACK'
